[package]
name = "gruntpy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "gruntpy"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.0"
grunt = { package="grunt", version="0.1.0", path="../../"}
